---
# Generado automaticamente por generate_host_vars.py
# Fecha: 2026-05-21T08:58:17
# Revisa entradas TODO_* antes de usar en renovaciones.

certificates:
- name: apps-lab-ulpgc-local
  cert_src: '{{ playbook_dir }}/../files/certs_input/apps.crt'
  key_src: '{{ playbook_dir }}/../files/certs_input/apps.key'
  cert_dest: /etc/nginx/ssl/apps.crt
  key_dest: /etc/nginx/ssl/apps.key
  owner: root
  group: root
  cert_mode: '0644'
  key_mode: '0600'
  service: nginx
  validate:
    host: '{{ ansible_host }}'
    port: 443
    sni: apps.lab.ulpgc.local
